frontend/project/server/api/views.py
from flask import render_template, jsonify, request, current_app, Blueprint
from flask import send_from_directory, url_for, redirect
from werkzeug.utils import secure_filename
from ..models.models import Node
from ..forms.upload_form import UploadForm
import redis
from rq import Queue, Connection
from rq.registry import StartedJobRegistry, FinishedJobRegistry

import json
import urllib.request
import requests

# from bs4 import BeautifulSoup

from ..forms.upload_form import TextForm, Nuts2Form

import numpy as np

import os
import csv
import time
import datetime
from dateutil import tz

import multiprocessing

from ..api import metas, utils
from ..services import vas
from ..services import actv_reg
from ..services import dist_rf
# from ..services.defs import *

from ...common.mqtt_utils import MqttLog
from ...common.defs import *

import random
from influxdb import DataFrameClient
from math import radians

api = Blueprint('api', __name__,)

feat_name_list = [
    "acc_x", "acc_y", "acc_z", "acc_comp",
    "lacc_x", "lacc_y", "lacc_z", "lacc_comp",
    "gra_x", "gra_y", "gra_z", "gra_comp",
    "gyr_x", "gyr_y", "gyr_z", "gyr_comp",
    "mag_x", "mag_y", "mag_z", "mag_comp",
    "ori_w", "ori_x", "ori_y", "ori_z", "pre"]

@api.route('/', methods=['GET'])
def home():
  return "{'hello':'world'}"

@api.route('/getallqueues', methods=['POST'])
def getallqeueues():
    return jsonify(metas.get_all_task_ids(current_app.config))

@api.route('/getqueuecount', methods=['POST'])
def getqueuecount():
  with Connection(redis.from_url(current_app.config['REDIS_URL'])):
    q = Queue()
  if q:
    return jsonify({'length': len(q)})
  else:
    return jsonify({'length': -1})

@api.route('/checkqueue', methods=['GET', 'POST'])
def checkqueue():
  with Connection(redis.from_url(current_app.config['REDIS_URL'])):
    q = Queue()
    if q:
      data = {}
      data['status'] = 'success'
      data['jobs_count'] = len(q)
      data['jobs'] = []
      for job_id in q.job_ids:
        job = q.fetch_job(job_id)
        task_status = job.get_status()
        task_result = job.result
        task_obj = {'task_id': job_id, \
                    'task_status': task_status, \
                    'task_result': task_result}
        data['jobs'].append(task_obj)

      return json.dumps({'response': data})

  return jsonify({'status': 'error'})

#https://stackoverflow.com/questions/15182696/multiple-parameters-in-in-flask-approute

@api.route('/task/<queue>/<task_id>', methods=['GET','POST'])
def get_status(queue = None, task_id = None):
  return jsonify(metas.get_task_status(queue, task_id, current_app.config))


@api.route('/queue_count', methods=['GET', 'POST'])#, 'OPTIONS'])
def queue_count():
  queue_out = {}
  csv_out = str(int(time.time()))
  csv_out += ','
  with Connection(redis.from_url(current_app.config['REDIS_URL'])):
    q = Queue('default')
    f_registry = FinishedJobRegistry('default')
    csv_out += str(len(q))
    csv_out += ','
    csv_out += str(len(f_registry.get_job_ids()))
  csv_out += '\n'
  return csv_out

@api.route('/getmetas', methods=['GET', 'POST'])
def getmetas():
  return jsonify(metas.get_meta_info(current_app.config))

@api.route('/get_exec_times', methods=['GET', 'POST'])
def get_exec_times():
  data = {}
  # Get the execution timing info
  data['exec_time_logs'] = metas.get_all_exec_time_logs()
  return jsonify(data)

@api.route('/get_exec_time/<unique_id>', methods=['GET', 'POST'])
def get_exec_time(unique_id):
  data = {}
  data['exec_time_logs'] = { unique_id : metas.get_exec_time_log(unique_id) }
  return jsonify(data)

@api.route('/set_redis', methods=['GET','POST'])
def set_redis():
  try:
    r = redis.StrictRedis(host="redis", port=6379, password="", decode_responses=True)
    r.set("msg:hello", "Hello Redis!!!")
    print(r.get("msg:hello"))
    return "Redis inserted"
  except Exception as e:
    print(e)

@api.route('/check_redis/<key>', methods=['GET','POST'])
def check_redis(key):
  r = redis.StrictRedis(host="redis", port=6379, password="", decode_responses=True)
  status = r.get(key)
  node_count = r.get(key + NODE_COUNT)
  done_node_count = r.get(key + DONE_NODE_COUNT)

  d = {'id': key, 'status': status, 'node_count': node_count, 'done_node_count': done_node_count}
  if status is not None:
    return jsonify(d)
  else:
    return "Empty"

@api.route('/get_redis', methods=['GET','POST'])
def get_redis():
  r = redis.StrictRedis(host="redis", port=6379, password="", decode_responses=True)
  output = r.get("msg:hello")
  if output is not None:
    return output
  else:
    return "Empty"

@api.route('/flush_redis', methods=['GET','POST'])
def flush_redis():
  with Connection(redis.from_url(current_app.config['REDIS_URL'])):
    queues = ['default', 'aggregator']

    for queue in queues:
      q = Queue(queue)
      f_registry = FinishedJobRegistry(queue)
      finished_job_ids = f_registry.get_job_ids()

      for f_job_id in finished_job_ids:
        j = q.fetch_job(f_job_id)
        j.cleanup(0)

  return "Flushed"

def fix_labels(label):
  #Labels
  #For feature extraction i think
  # %%time
  reshape_label = label.reshape(len(label)//window_size, window_size)

  correct_label = []

  for i in range(reshape_label.shape[0]):
      rows = reshape_label[i, :]
      unique, counts = np.unique(rows, return_counts=True)
      out = np.asarray((unique, counts)).T
      if out[0][1] != float(window_size):
          max_ind = np.argmax(np.max(out, axis=1))
          correct_label.append(out[max_ind, 0])
      elif out[0][1] == float(window_size):
          correct_label.append(out[0][0])

  y = np.array(correct_label)
  print(y.shape)
  return y

TARGET_NAMES = ["still", "walk",  "run",  "bike",  "car",  "bus",  "train",  "subway"]
NUM_CLASSES = len(TARGET_NAMES)
window_size = 100

def enqueue_npy_files(unique_ID, model_type, chunk_list, mp_q):
  label_list = []
  data_list = []
  np_data_arrays = []
  with Connection(redis.from_url(current_app.config['REDIS_URL'])):
    q = Queue('default')
    print("Handling chunks: ", chunk_list)
    for chunk in chunk_list:
      filename = 'labels_' + str(chunk) + '.npy'
      path = os.path.join(current_app.instance_path, 'htmlfi/Chunks', filename)
      label = np.load(path)
      label_list.append(label)

      for i, name in enumerate(feat_name_list):
        raw_filename = name + '_' + str(chunk) + '.npy'
        raw_path = os.path.join(current_app.instance_path, 'htmlfi/Chunks', raw_filename)
        np_temp = np.load(raw_path)
        if len(np_data_arrays) == len(feat_name_list):
          np_data_arrays[i].extend([np_temp])
        else:
          np_data_arrays.append([np_temp])

    label_all = np.concatenate(label_list)
    y = fix_labels(label_all)
    y_str = y.tostring()

    for np_data_array in np_data_arrays:
      np_all = np.concatenate(np_data_array)
      all_str = np_all.tostring()
      data_list.append(all_str)

    task = q.enqueue('NUTS_Tasks.feat_Extract_And_Classify', data_list, y_str, model_type, unique_ID)
    response_object = {
        'status': 'success',
        'unique_ID': 'NUTS FEAT EXTRACT',
        'data_list_len': len(data_list[0]),
        'y_str_len': len(y_str),
        'model_type': model_type,
        'chunk_list': chunk_list,
        'data': {
          'task_id': task.get_id()
      }
    }
    mp_q.put(response_object)

#TODO: Fix for moren odes above 3
@api.route('/nuts_classify', methods=['GET', 'POST'])#, 'OPTIONS'])
def nuts_classify():
  with Connection(redis.from_url(current_app.config['REDIS_URL'])):
    q = Queue('default')
    #form = TextForm(meta={'csrf_context': request.remote_addr})
    form = TextForm(meta={'csrf_context': 'secret_key'})
    if form.validate_on_submit():
      tic = time.clock()
      node_count = form.node_count.data
      number_of_chunks = form.chunk_count.data
      model_type = form.model_type.data

      if node_count > number_of_chunks:
        #Maybe i should just divide the chunks, no! haha 
        return jsonify({'status':'node_count is greater than chunk_count'}), 616

      unique_ID = utils.initialize_query(node_count)
      total_chunks = 200 #hard coded because i only saved 15 chunks in the server
      #Now need to make everything into lists
      chunks = []
      while len(chunks) != number_of_chunks:
        single_chunk = np.random.randint(0, total_chunks)
        if single_chunk in chunks:
          continue
        else:
          chunks.append(single_chunk)

      div, mod = divmod(number_of_chunks, node_count)

      index = 0
      chunk_lists = []
      node_data_list = []
      node_label_list = []

      for i in range(node_count):
        slice = chunks[index: index + div]
        index += div
        chunk_lists.append(slice)

      for i in range(mod):
        slice = chunks[index: index + div]
        chunk_lists[i].extend(slice)
        index += div

      #For debugging, need 202 return no.
      # return jsonify(chunk_lists[0]), 202

      json_response = {}
      json_response['tasks'] = []
      json_response['query_ID'] = unique_ID
      #json_response['query_received'] = int(time.time())
      json_response['query_received'] = utils.get_current_time()

      out_q = multiprocessing.Queue()
      procs = []
      for chunk_list in chunk_lists:
        p = multiprocessing.Process(target=enqueue_npy_files, args=(unique_ID, model_type, chunk_list, out_q))
        procs.append(p)
        p.start()

      for chunk_list in chunk_lists:
        json_response['tasks'].append(out_q.get())

      for p in procs:
        p.join()

      toc = time.clock()
      json_response['progress'] = toc - tic
      return jsonify(json_response), 202
    elif form.csrf_token.errors:
      return jsonify({'status':'csrf_token_errors'})
    else:
      return jsonify({'status':'error'})

@api.route('/nuts2_classify', methods=['GET', 'POST'])#, 'OPTIONS'])
def nuts2_classify():
  with Connection(redis.from_url(current_app.config['REDIS_URL'])):

frontend/project/server/main/views.py
from flask import render_template, jsonify, request, current_app, Blueprint
from flask import send_from_directory, url_for, redirect
from werkzeug.utils import secure_filename
from ..models.models import Node
from ..forms.upload_form import UploadForm, TextForm
from rq import Queue, Connection
import redis
import os
from project.server.main.tasks import create_task
import json
from rq.registry import StartedJobRegistry, FinishedJobRegistry
import urllib.request, json 
import requests
import csv
from . import funcs

#Move to constants file.
NODE_COUNT = '_node_count'
DONE_NODE_COUNT = '_done_node_count'
NODES = '_nodes'

main_blueprint = Blueprint('main', __name__,)

@main_blueprint.route('/', methods=['GET'])
def home():
  n = Node(name='Master')
  print(n)
  return render_template('main/home.html', debug=n)

@main_blueprint.route('/upload', methods=['GET', 'POST'])
def upload():
  form = UploadForm()
  if form.validate_on_submit():
    file = form.file.data
    if file and funcs.allowed_file(file.filename):
      filename = secure_filename(file.filename)
      os.makedirs(os.path.join(current_app.instance_path, 'htmlfi'), exist_ok=True)
      file.save(os.path.join(current_app.instance_path, 'htmlfi', filename))

      return redirect(url_for('main.uploaded_file', filename=filename))
  return render_template('main/upload.html', form=form, result=None)

@main_blueprint.route('/jp')
def jp():
  return redirect(url_for('api.home'))

#https://stackoverflow.com/questions/19794695/flask-python-buttons
#https://stackoverflow.com/questions/43811779/use-many-submit-buttons-in-the-same-form
@main_blueprint.route('/iris_classifier', methods=['GET', 'POST'])
def iris_classifier():
  form = UploadForm()
  if request.method == 'POST':
    if form.validate_on_submit():
      file = form.file.data
      if file and funcs.allowed_file(file.filename):
        filename = secure_filename(file.filename)
        os.makedirs(os.path.join(current_app.instance_path, 'htmlfi'), exist_ok=True)
        file.save(os.path.join(current_app.instance_path, 'htmlfi', filename))
        print(filename)
        submit_val = request.form['action']
        print(submit_val)
        if submit_val == 'Single':
          return redirect(url_for('main.start_iris_process', filename=filename))
        elif submit_val == 'Distributed':
          return redirect(url_for('main.start_iris_dist_process', filename=filename))
        else:
          pass # unknown
  elif request.method == 'GET':
      return render_template('main/upload.html', form=form, result=None)

@main_blueprint.route('/nuts_classifier', methods=['GET', 'POST'])
def nuts_classifier():
  form = TextForm(meta={'csrf_context': request.remote_addr})
  if request.method == 'GET':
    return render_template('main/nuts.html', form=form)
  elif request.method == 'POST':
    if form.validate_on_submit():
      node_count = form.node_count.data
      chunk_count = form.chunk_count.data
      model_type = form.model_type.data
      return jsonify(data={'node_count': node_count, 'chunk_count': chunk_count, 'model_type': model_type})
    elif form.csrf_token.errors:
      pass # If we're here we suspect the user of cross-site request forgery
    else:
      return "Error"

#Later on add choice to control the number of nodes and/or the number of data points/chunks/queries at once
@main_blueprint.route('/nuts_dist_process', methods=['GET', 'POST'])
def start_nuts_dist_process():
  form = TextForm(meta={'csrf_context': request.remote_addr})
  if form.validate_on_submit():
    node_count = form.node_count.data
    chunk_count = form.chunk_count.data
    model_type = form.model_type.data
    # node_count = request.args.get("node_count")
    # model_type = request.args.get("model_type")
    # chunk_count = request.args.get("chunk_count")

    json = {
            'node_count': node_count,
            'model_type': model_type,
            'chunk_count': chunk_count
            }

    #Can i not hardcode the link?
    res = requests.post('http://163.221.68.242:5001/api/nuts_classify', json=json)

    #Trigger continuous updates here with time
    return res.text
  else:
    return "Error"

#Dist
@main_blueprint.route('/iris_dist_process', methods=['GET', 'POST'])
def start_iris_dist_process():
  # filename = secure_filename(request.args.get("filename"))
  # split(filename, 3)

  filename = secure_filename(request.args.get("filename"))
  redis_conn = redis.from_url(current_app.config['REDIS_URL'])
  print(filename)
  try:
    if filename and funcs.allowed_file(filename):
      u_ID = funcs.generate_unique_ID()
      with open(os.path.join(current_app.instance_path, 'htmlfi', filename)) as f:
        q = Queue(connection = redis_conn)
        nodes = 3
        #Split file into 3
        files = funcs.split(filename, 3)

        funcs.setRedisKV(redis_conn, u_ID, 'ongoing')
        funcs.setRedisKV(redis_conn, u_ID + NODE_COUNT, nodes)
        funcs.setRedisKV(redis_conn, u_ID + DONE_NODE_COUNT, 0)

        #assuming the files are in sequential order, we can send some sequence id to the queue
        for sequence_ID, file in enumerate(files):
          data = file.read()
          #Need to decode?
          #Race condition i think.
          task = q.enqueue('tasks.classify_iris_dist', data, nodes, u_ID, sequence_ID)

      return 'Classifying Distributedly...'
  except IOError:
    pass
  return "Unable to read file"


@main_blueprint.route('/iris_process', methods=['GET', 'POST'])
def start_iris_process():
  filename = secure_filename(request.args.get("filename"))
  redis_conn = redis.from_url(current_app.config['REDIS_URL'])
  print(filename)
  try:
    if filename and funcs.allowed_file(filename):
      with open(os.path.join(current_app.instance_path, 'htmlfi', filename)) as f:
        data = f.read()
        q = Queue(connection = redis_conn)
        task = q.enqueue('tasks.classify_iris', data)
      return 'Classifying...'
  except IOError:
    pass
  return "Unable to read file"

@main_blueprint.route('/uploads/<filename>')
def uploaded_file(filename):
  return send_from_directory(os.path.join(current_app.instance_path, 'htmlfi'), filename)

@main_blueprint.route('/tasks', methods=['POST'])
def run_task():
  print(dir())
  task_type = request.form['type']
  r = redis.StrictRedis(host="redis", port=6379, password="", decode_responses=True)

  u_ID = funcs.generate_unique_ID()
  with Connection(redis.from_url(current_app.config['REDIS_URL'])):
    q = Queue()
    funcs.setRedisKV(r, u_ID, 'ongoing')
    funcs.setRedisKV(r, u_ID + NODE_COUNT, 1)
    funcs.setRedisKV(r, u_ID + DONE_NODE_COUNT, 0)

    task = q.enqueue('tasks.create_task', task_type, u_ID)
  response_object = {
      'status': 'success',
      'unique_ID': u_ID,
      'data': {
        'task_id': task.get_id()
    }
  }
  return jsonify(response_object), 202

frontend/project/client/templates/main/home.html
{% extends "_base.html" %}

{% block content %}

<div class="starter-template">
  <h1>HOME</h1>
  Hello world!
  debug: {{ debug }}
  <br>
  <button type="button" class="btn btn-primary" data-type="1">Run 10 second task</button>
  <button type="button" class="checkQueue btn-primary" data-type="1">Check queue</button>
  <button type="button" class="getAllQueues btn-primary" data-type="1">Get all tasks</button>
  <br><br>
  <button type="button" class="getmetas btn-primary" data-type="1">Watch tasks</button>
  <button type="button" class="test_redis btn-primary" data-type="1">set Redis</button>
  <button type="button" class="get_redis btn-primary" data-type="1">get Redis</button>
  <br><br>
  <button type="button" class="flush_redis btn-primary" data-type="1">Flush Redis</button>
  <button type="button" class="test_nuts btn-primary" data-type="1">Test_Nuts</button>
  <br><br>
  <table style="width:50%">
    <td><a href={{ url_for('main.iris_classifier') }} target="_blank">iris_classifier</a></td>
    <td><a href={{ url_for('main.nuts_classifier') }} target="_blank">nuts_classifier</a></td>
  </table>
  <br><br>
</div>

<div class='my-legend'>
<div class='legend-title'>Task Color Legend *Default = Processor</div>
<div class='legend-scale'>
  <ul class='legend-labels'>
    <li><span style='background:#337CFF;'></span>Running default task</li>
    <li><span style='background:#E4FF33;'></span>Queued default task</li>
    <li><span style='background:#33FF55;'></span>Finished default task</li>
    <li><span style='background:#69E0D3;'></span>Finished aggregator task</li>
    <li><span style='background:#80B1D3;'></span>etc</li>
  </ul>
</div>
<div class='legend-source'>Source: <a href="#link to source">Name of source</a></div>
</div>

<div>
	<h3>Task Status</h3>
	<div id="status"></div>
	<br>
	<table style="width:100%">
		<thead>
		  <tr  class="header expand">
				<th colspan="1">Handled Time <span class="sign"></span></th>
				<th>ID</th>
				<th>Handler</th>
				<th>Progress</th>
				<th>Status</th>
				<th>Result</th>
			</tr>
		</thead>
		<tbody id="tasks">
		</tbody>
	</table>
</div>

{% endblock %}

frontend/project/client/templates/main/nuts.html
<!DOCTYPE html>
  <html>
    <head>
      <title>Example Post AJAX Out get JSON Back</title>
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <script src="http://code.jquery.com/jquery-1.8.3.min.js"></script>
      <script>
      // Just query api/nuts_classify after click, i think
      $(document).ready(function() {
        $('form').submit(function (e) {
            var url = "{{ url_for('api.nuts_classify') }}"; // send the form data here.
            $.ajax({
                type: "POST",
                url: url,
                data: $('form').serialize(), // serializes the form's elements.
                success: function (data) {
                  console.log(data);  // display the returned data in the console.
                  // alert(data);
                },
                error: function (request, status, error) {
                  console.log(status);
                  console.log(error);
                  console.log(request);
                },
                complete: function () {
                  // Handle the complete event
                  alert("ajax completed");
                }
            });
            e.preventDefault(); // block the traditional submission of the form.
        });
        // Inject our CSRF token into our AJAX request.
        $.ajaxSetup({
            beforeSend: function(xhr, settings) {
                if (!/^(GET|HEAD|OPTIONS|TRACE)$/i.test(settings.type) && !this.crossDomain) {
                    xhr.setRequestHeader("X-CSRFToken", "{{ form.csrf_token._value() }}")
                }
            }
        })
      });
      </script>
    </head>

    <body>

    {% for message in form.node_count.errors %}
         <div>{{ message }}</div>
    {% endfor %}
    {{ form.csrf_token }}
    <form method="post">
      {{ form.chunk_count.label }} (1-200)
      {{ form.chunk_count }}
      <br>
      {{ form.node_count.label }} (1-3)
      {{ form.node_count }}
      <br>
      {{ form.model_type.label }}
      {{ form.model_type }}
      <br>
      {{ form.hidden_tag() }}
      <input type="submit" value="Go"/>
    </form>

    <!-- Updating table here -->
    </body>
  </html>

frontend/project/client/templates/main/upload.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Flask app</title>
  </head>
  <body>
    <h2>Input:</h2>
    <form method="post" action="" enctype="multipart/form-data">
      <table>
        {% for field in form %}
          <tr>
            <td>{{ field.name }}</td>
            <td>{{ field(size=20) }}</td>
            <td>
              {% if field.errors %}
                <ul class=errors>
                  {% for error in field.errors %}
                    <li>{{ error }}</li>
                  {% endfor %}
                </ul>
              {% endif %}
            </td>
          </tr>
        {% endfor %}
      </table>
      <div class="panel-body">
          <input type ="submit" name="action" value="Single">
      </div>
      <div class="panel-body">
          <input type ="submit" name="action" value="Distributed">
      </div>
      
    </form>
    {% if result != None %}
      <h2>Results:</h2>
      {{ result|safe }}
    {% endif %}
  </body>
</html>